SCREEN_WIDTH = 80
SCREEN_HEIGHT = 60
LIMIT_FPS = 20

MAP_WIDTH = 80
MAP_HEIGHT = 45
BAR_WIDTH = 20

PANEL_HEIGHT = 7
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1

INVENTORY_WIDTH = 50
